version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server

  client:
    build:
      context: ./insighthub-frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "5001:80"

  server:
    build:
      context: ./insighthub-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - ./insighthub-backend/.env.prod