version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "443:3000"
    env_file:
      - ./insighthub-backend/.env.prod
    volumes:
      - ./ssl:/ssl
